### ISSUE TITLE
Make `textarea` honor `cols`

### ISSUE THREAD

**Issue by dolanske** [dolanske/vui#91]

**Comment by dolanske** [comment]
Could be done via CSS when height / width not set

```css
textarea:not([rows]) {
  min-height: 10em;
}
```
